// Copyright 2019 Google Inc.  All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <string>
#include <map>
#include <vector>

#include "absl/strings/str_cat.h"
#include "absl/strings/string_view.h"
#include "absl/strings/str_replace.h"
#include "generator/gapic_generator.h"
#include "internal/gapic_utils.h"
#include "internal/printer.h"

#include "google/api/client.pb.h"

namespace pb = google::protobuf;

namespace google {
namespace api {
namespace codegen {

using Vars = std::map<std::string, std::string>;

void SetServiceVars(
    pb::ServiceDescriptor const* service,
    std::map<std::string, std::string>& vars) {
  vars["class_name"] = service->name();
  vars["proto_file_name"] = service->file()->name();
  vars["header_include_guard_const"] = absl::StrCat(service->name(), "_H_");
  vars["class_comment_block"] = "// TODO: pull in comments";
  vars["grpc_stub_fqn"] = internal::ProtoNameToCppName(service->full_name());
  vars["service_endpoint"] = service->options().GetExtension(google::api::default_host);
}

void SetMethodVars(
    pb::MethodDescriptor const* method,
    std::map<std::string, std::string>& vars) {
  vars["method_name"] = method->name();
  vars["request_object"] = internal::ProtoNameToCppName(method->input_type()->full_name());
  vars["response_object"] = internal::ProtoNameToCppName(method->output_type()->full_name());
}

std::vector<std::string> BuildHeaderIncludes(
    pb::ServiceDescriptor const* /* service */) {
  return std::vector<std::string>();
}

std::vector<std::string> BuildCCIncludes(
    pb::ServiceDescriptor const* /* service */) {
  return std::vector<std::string>();
}

std::vector<std::string> BuildNamespaces(
    pb::ServiceDescriptor const* /* service */) {
  return std::vector<std::string>();
}

void PrintMethods(
    pb::ServiceDescriptor const* service,
    std::map<std::string, std::string> vars,
    internal::Printer& p,
    char const* tmplt) {
  for (int i = 0; i < service->method_count(); i++) {
    const pb::MethodDescriptor* method = service->method(i);
    SetMethodVars(method, vars);
    p->Print(vars, tmplt);
  }
}

bool GenerateClientHeaderFile(
    pb::ServiceDescriptor const* service,
    std::map<std::string, std::string> const& vars,
    internal::Printer& p,
    std::string * /* error */) {
  auto includes = BuildHeaderIncludes(service);
  auto namespaces = BuildNamespaces(service);

  p->Print(vars,
    "// Generated by the GAPIC C++ plugin.\n"
    "// If you make any local changes, they will be lost.\n"
    "// source: $proto_file_name$\n"
    "#ifndef $header_include_guard_const$\n"
    "#define $header_include_guard_const$");

  for (auto include : includes) {
    p->Print("\n#include $include$", "include", include);
  }
  for (auto nspace : namespaces) {
    p->Print("\nnamespace $namespace$ {", "namespace", nspace);
  }

  p->Print(vars, "\n"
    "$class_comment_block$\n"
    "class $class_name$ {");

  PrintMethods(service, vars, p, "");

  p->Print(vars, "\n}; // $class_name$");

  for (auto nspace : namespaces) {
    p->Print("\n} // namespace $namespace$", "namespace", nspace);
  }

  p->Print(vars, "\n"
    "#endif // $header_include_guard_const$\n");

  return true;
}

bool GenerateClientCCFile(
    pb::ServiceDescriptor const* service,
    std::map<std::string, std::string> const& vars,
    internal::Printer& p,
    std::string * /* error */) {
  auto includes = BuildCCIncludes(service);
  auto namespaces = BuildNamespaces(service);

  p->Print(vars,
    "// Generated by the GAPIC C++ plugin.\n"
    "// If you make any local changes, they will be lost.\n"
    "// source: $proto_file_name$");

  for (auto include : includes) {
    p->Print("\n#include $include$", "include", include);
  }
  for (auto nspace : namespaces) {
    p->Print("\nnamespace $namespace$ {", "namespace", nspace);
  }

  p->Print(vars, "\n"
    "// TODO: add content");

  for (auto nspace : namespaces) {
    p->Print("\n} // namespace $namespace$", "namespace", nspace);
  }

  p->Print("\n");

  return true;
}

bool GapicGenerator::Generate(pb::FileDescriptor const* file,
                                 std::string const& /* parameter */,
                                 pb::compiler::GeneratorContext* generator_context,
                                 std::string* error) const {
  if (file->options().cc_generic_services()) {
    *error =
        "cpp gapic proto compiler plugin does not work with generic "
        "services. To generate cpp grpc APIs, please set \""
        "cc_generic_service = false\".";
    return false;
  }

  for (int i = 0; i < file->service_count(); i++) {
    pb::ServiceDescriptor const* service = file->service(i);

    // TODO(michaelbausor): initialize Vars with cross-file-descriptor
    // configuration, e.g. metadata annotation.
    std::map<std::string, std::string> vars;
    SetServiceVars(service, vars);

    std::string service_file_path = internal::ServiceNameToFilePath(
        service->full_name());

    std::string header_file_path = absl::StrCat(service_file_path, ".gapic.h");
    internal::Printer header_printer(generator_context, header_file_path);
    if (!GenerateClientHeaderFile(service, vars, header_printer, error)) {
      return false;
    }

    std::string cc_file_path = absl::StrCat(service_file_path, ".gapic.cc");
    internal::Printer cc_printer(generator_context, cc_file_path);
    if (!GenerateClientCCFile(service, vars, cc_printer, error)) {
      return false;
    }
  }
  return true;
}

} // namespace codegen
} // namespace api
} // namespace google
