// Copyright 2019 Google Inc.  All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef GOOGLE_API_CODEGEN_INTERNAL_GAPIC_HEADER_TEMPLATES_H_
#define GOOGLE_API_CODEGEN_INTERNAL_GAPIC_HEADER_TEMPLATES_H_

#include <memory>

namespace google {
namespace api {
namespace codegen {
namespace internal {

constexpr char kHeaderFileStartTemplate[] =
R"(// Generated by the GAPIC C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$
#ifndef $header_include_guard_const$
#define $header_include_guard_const$)";

constexpr char kHeaderClientStartTemplate[] = R"(
$class_comment_block$
class $class_name$ {)";

constexpr char kHeaderClientMethodTemplate[] = "";

constexpr char kHeaderClientEndTemplate[] = R"(
}; // $class_name$
#endif // $header_include_guard_const$
)";

} // namespace internal
} // namespace codegen
} // namespace api
} // namespace google

#endif // GOOGLE_API_CODEGEN_INTERNAL_GAPIC_HEADER_TEMPLATES_H_
